#!/usr/bin/env bash
# fund-demo-accounts.sh
# Generates the 6 PharmaGuard demo EOAs, writes them into .env, and claims
# Monad testnet funds for each from the monskills faucet.
#
# Usage (from repo root):  bash scripts/fund-demo-accounts.sh
#
# Safe to re-run: an existing .env is backed up to .env.bak.<timestamp> first.
# These are throwaway TESTNET keys — never reuse real keys here.
set -uo pipefail

# --- config ---
RPC="https://testnet-rpc.monad.xyz"
CHAIN_ID="10143"
FAUCET="https://agents.devnads.com/v1/faucet"
TOKEN_URI="https://pharmaguard.example/metadata/{id}.json"
ROLES=(ADMIN ORACLE MANUFACTURER DISTRIBUTOR PHARMACY_A PHARMACY_B)

# --- foundry on PATH (cast is installed but not auto-on-PATH in fresh shells) ---
export PATH="$PATH:/c/Users/$USER/.foundry/bin:$HOME/.foundry/bin"
if ! command -v cast >/dev/null 2>&1; then
  echo "ERROR: 'cast' (Foundry) not found. Install Foundry or fix PATH." >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

# --- back up an existing .env so we never clobber work ---
if [ -f "$ENV_FILE" ]; then
  bak="$ENV_FILE.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$ENV_FILE" "$bak"
  echo "Existing .env backed up to: $bak"
fi

# --- generate keypairs ---
declare -A ADDR
declare -A PK
echo "Generating 6 demo keypairs..."
for role in "${ROLES[@]}"; do
  out="$(cast wallet new)"
  ADDR[$role]="$(echo "$out" | awk '/Address:/{print $2}')"
  PK[$role]="$(echo "$out" | awk '/[Pp]rivate key:/{print $NF}')"
  if [ -z "${ADDR[$role]}" ] || [ -z "${PK[$role]}" ]; then
    echo "ERROR: failed to parse keypair for $role from: $out" >&2
    exit 1
  fi
done

# --- write .env ---
{
  echo "# Generated by scripts/fund-demo-accounts.sh ($(date)) — TESTNET ONLY"
  echo "MONAD_RPC_URL=$RPC"
  echo "MONAD_CHAIN_ID=$CHAIN_ID"
  echo "TOKEN_URI=$TOKEN_URI"
  echo ""
  echo "# Filled after deploy (forge script Deploy ... --broadcast)"
  echo "CONTRACT_ADDRESS="
  echo ""
  echo "# Demo account private keys (testnet throwaway)"
  for role in "${ROLES[@]}"; do
    echo "${role}_PK=${PK[$role]}"
  done
} > "$ENV_FILE"
echo "Wrote $ENV_FILE"

# --- claim faucet funds for each address ---
echo ""
echo "Claiming testnet funds (chainId $CHAIN_ID)..."
for role in "${ROLES[@]}"; do
  a="${ADDR[$role]}"
  resp="$(curl -s -X POST "$FAUCET" -H "Content-Type: application/json" \
    -d "{\"chainId\": $CHAIN_ID, \"address\": \"$a\"}")"
  echo "  $role  $a  ->  ${resp:-<no response>}"
  sleep 2  # be gentle with faucet rate limits
done

# --- wait for balances (best-effort, 60s cap) ---
echo ""
echo "Waiting for balances to land (up to 60s)..."
deadline=$(( $(date +%s) + 60 ))
for role in "${ROLES[@]}"; do
  a="${ADDR[$role]}"
  while :; do
    bal="$(cast balance "$a" --rpc-url "$RPC" 2>/dev/null || echo 0)"
    [ "$bal" != "0" ] && break
    [ "$(date +%s)" -ge "$deadline" ] && break
    sleep 2
  done
  printf "  %-12s %s  balance=%s wei\n" "$role" "$a" "$bal"
done

echo ""
echo "Done. Summary:"
for role in "${ROLES[@]}"; do
  printf "  %-12s %s\n" "$role" "${ADDR[$role]}"
done
echo ""
echo "Next: cd contracts && forge script script/Deploy.s.sol:Deploy --rpc-url \"$RPC\" --broadcast"
echo "Then put the deployed address into .env as CONTRACT_ADDRESS and run SeedRoles."
